# Generated by Django 5.1.3 on 2024-11-13 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('store', '0002_alter_category_options_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
