# Generated by Django 5.1.3 on 2024-11-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_Product',
        ),
    ]
