# Generated by Django 5.1.3 on 2024-11-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_cart',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
