# Generated by Django 5.1.3 on 2024-11-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
